# Generated by Django 3.2.4 on 2021-07-02 12:15

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korepetycje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_count', models.IntegerField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.ManyToManyField(blank=True, to='korepetycje.Subject'),
        ),
    ]
