# Generated by Django 3.2.4 on 2021-07-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korepetycje', '0002_auto_20210702_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Post',
        ),
    ]
