# Generated by Django 3.2.5 on 2021-07-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korepetycje', '0003_rename_page_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
